server:
  port: 16600

spring:
  datasource:
    username: root
    password: Qubaba8888....
    url: jdbc:mysql://192.168.62.132:3306/fly_auth
    driver-class-name: com.mysql.cj.jdbc.Driver
    # driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 192.168.62.132

management:
  server:
    port: 16601
  endpoints:
    web:
      exposure:
        include: '*'
