server:
  port: 8080

spring:
  application:
    name: auth-server
  datasource:
    username: root
    password: Qubaba8888....
    url: jdbc:mysql://192.168.62.133:3306/fly_auth
    driver-class-name: com.mysql.cj.jdbc.Driver
    # driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 192.168.62.133
  cloud:
    nacos:
      server-addr: 192.168.62.133:8848
    gateway:
      routes:
        - id: auth-server
          uri: http://www.google.com
          predicates:
          - Path=/auth-server/*