server:
  port: 10060

spring:
  redis:
    host: 192.168.62.132
  datasource:
    username: root
    password: Qubaba8888....
    url: jdbc:mysql://192.168.62.132:3306/fly_auth
    driver-class-name: com.mysql.cj.jdbc.Driver
management:
  server:
    port: 10061
  endpoints:
    jmx:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: when_authorized
      roles: 'ADMIN'
